commands/init.go

Currently, when `brave init` is called without arguments on Windows the command fails and prints a "OS not supported" message.
Instead, it would make sense to set the backend to multipass by default and proceed with the initialization.

Windows default backend set to multipass

---

platform/host_api.go
platform/operations.go

1) Explicitly close files after writing to them, before performing further operations on the file (e.g. remove, rename).
This fixes issues encountered in Windows while building new images. (https://github.com/bravetools/bravetools/issues/8)
2) Formalize use of double close pattern for os.File to ensure files are closed in case of err
https://github.com/golang/go/issues/20705

Ensure files are closed by Bravetools before removing/renaming

---

platform/host_api.go
platform/operations.go
shared/brave_unit.go

Addresses issue #20 by changing Disk to an array object rather than a string. `brave units` now lists both no mounts, single mounts, and multiple mounts.

address #20

---

platform/helpers.go

This is a backward-compatible change to address a bug introduced by https://github.com/lxc/lxd/pull/9946
The main issue is around name of a proxy device. Historically, we use `:` in proxy device names. This is now replaced by `-` to avoid the incompatibility error when trying to delete units.

address #49

---

docs/docs/bravefile.md
platform/host_api.go

The docs refer to a location type "private" which does not exist. When an invalid location is supplied, a helpful error message will be returned

Fix docs to refer to "local" images rather than "private" images

---

commands/base.go
commands/build.go
platform/helpers.go
platform/host_api.go

This would better represent what is actually happening conceptually - an image is being built, from which units can be deployed.

Rename function BuildUnit to BuildImage 

---

platform/operations.go

Simple fix to make sure that retry first redirects to stdout before redirecting to stderr if fails

Spinner stdout redirect

---

platform/helpers.go
platform/host_api.go

Importing base images from public LXD servers set the fingerprint string, but other paths in the code left the image fingerprint at its default value (""), causing it to be impossible to delete image by fingerprint later. This would happen when the image base location was set to local. To address the problem, all import functions also return the image fingerprint when done.
This change allows for proper cleanup of images after build completion or in event of failure.
Also added cleanup of local image if `importLocal` fails to start a unit.
Together these should helps address problems caused by LXD images hanging around after a build, preventing future builds that attempt to use that alias.

Return image fingerprint when building from base local/github images

---

README.md

Although network name was updated in the README, the LXD profile and storage pool name were not.

Update README with the new names for the LXD profile and storage pool

---

platform/host_api.go

Currently, if a typo is made when specifying the package manager, bravetools will silently skip the package installation phase of the build without any warning. This can lead to "successfully" publishing containers that don't actually work due to the lacking dependencies.

Return an error when an unrecognized package manager is encountered.

---

platform/host_api.go

This builds on previous fix and covers the edge case mentioned in https://github.com/bravetools/bravetools/pull/81 where if the user forgets to specify the package manager the section is skipped even if packages are to be installed. Makes sense to return a specific error in this case. 
In addition, removing the `fallthrough` statement prevents the execution of `apk update --no-cache` from the next block in the switch statement in the event of an empty package manager, which does not seem intended.

Raise error if empty package manager and packages to be installed

---

platform/helpers.go
platform/host.go
platform/multipass.go
platform/operations.go

bravetools uses the current username for:
- Multipass VM name
- LXD profile name
- LXD storage pool name
- LXD network bridge name
However, there are various rules regarding valid names for the above. In particular, multipass VM names and LXD network bridge names are most likely to cause issues.
- LXD network bridge names are limited to 15 characters maximum
- Multipass VM names are generally restricted to most alpha-numeric characters. A hyphen is allowed, but only in some cases (for example leading/trailing hyphen is not).
This pull request attempts to sanitize usernames so that they are valid for all the above uses. It is purposefully overly-cautious by stripping any non alpha-numeric charcaters to avoid dealing with those edge cases (for now). The username is actually restricted to 12 …

Username sanitization

---

commands/init.go

The err value of the cleanup code was overwriting the original err value. Often, the cleanup code would complete without error, leading to the masking of the true root cause of the error - bravetools would only report error "<nil>" and exit.
With this change, errors during cleanup are tracked and logged without terminating the program early and masking the original error.

Prevent shadowing of original error in init code

---

platform/multipass.go

Since multipass version 1.7.0 [windows mounts have been disabled by default by multipass](https://multipass.run/docs/privileged-mounts). This sets the required flag to true to enable mounts on Windows.
The command to change the flag is set to only run when Go is running on Windows OS. Older versions of multipass will not have this flag, so errors are logged but do not result in termination of build.

Enable privileged mounts on windows to allow mounting using multipass

---

platform/operations.go

Small bugfix to address specific `apk update` issue.
Running apk update does not close the DataDone channel unlike most other commands, leading to waiting for prompt from user before continuing. To address this use a goroutine to call op.Wait and close a channel to signal completion to select call instead.

Address apk update pause

---

db/db_operations_test.go

This allows the tests to run without running into errors. Previously, the `OpenDB` function would create a DB if it did not already exist, but this was changed in 59530704 to avoid issues with empty db files being created.
A test DB will be created prior to running tests and then deleted after the conclusion of all the tests.
The tests themselves could still use some more work to be more useful at testing the happy path, but at least with these issues the tests can run to completion without errors.

Update DB tests with initialization and teardown

---

platform/host_api.go
platform/lxd.go

Currently bravetools runs commands querying for `which lxc` and for the LXD version on the machine running bravetools within `InitUnit` using the functions `lxdCheck` and `checkLXDVersion`. Currently these functions don't account for the possibility of being called with multiple backends. This leads to errors when using a "multipass" backend - it means it isn't possible to deploy units at all on Windows.
This fix changes these functions to account for the possibility of being called from a mutlipass backend, which solves the isue and allows for deployments on multipass backends.
There may be alternative solutions - perhaps adding the path to lxc binary to the information returned by `Backend.Info`?

Account for multipass backend in `lxdCheck` and `checkLXDVersion`

---

commands/deploy.go
shared/bravefile.go
shared/constants.go

Pulling this out of https://github.com/bravetools/bravetools/pull/54 since it really is a separate change.
Currently, if attempting to deploy an image from a Bravefile that has no resources defined and without providing an image name from command line, the program will panic. In this branch, the default resources (RAM/CPU) are applied if they are left at empty values in the Bravefile, which feels more direct.
By doing this in a central place (Bravefile.Load) these defaults will apply however units are deployed (using `brave deploy` or perhaps in future `brave compose`).

Apply unit default resource limitations to bravefiles on load

---

docs/installation/uninstall-bravetools.md

Uninstallation instructions are more closely related to the Installation section than to the content in the section it currently is in "Docs". The "Docs" section is more focused on usage of `bravetools` (CLI reference, Bravefiles...) than installation/uninstallation.

Move uninstallation docs to `Install Bravetools` section

---

platform/operations.go

When running `brave init` on Windows I have been consistently encountering the following error which interrupts the init:
- 2022/07/14 16:43:57 failed to add remote host: The provided certificate isn't valid yet
It appears that [LXD recently changed their cert validation](https://github.com/lxc/lxd/blame/df84330299d1849c377a2d675874c947a490c94f/lxd/certificates.go#L1134), which seems to have tightened restrictions as this didn't happen before.
The problem likely occurs due to time-sync issues between the host and VM, since the certificate is already valid according to the host but gets rejected by LXD running inside of multipass.
Addding a short 5-second sleep after retrieving remote LXD cert appears to help prevent time sync issues between VM and host from causing the cert to be judged …

Wait for LXD cert to become valid

---

platform/helpers.go
platform/host_api.go

Currently errors from commands and their exit codes are only checked once at the end of `bravefileRun` function after looping through all commands. However, this means that only errors encountered on the last command will be caught - any earlier errors are overwritten by the last command. This means an error in early stages of bravefileRun will be swallowed silently.
Instead, we can check for errors on every iteration of loop runinng commands in bravefile run section and return early if we find any. This will prevent errors from earlier commands being overwritten and ignored.
To make this change, I needed to interpret non-zero exit codes as errors in `bravefileRun` function itself to terminate the loop. This was done anyway in host_api.go so should cause any new issues.

Swallowed errors in bravefile run

---

commands/deploy.go
platform/helpers.go
platform/host_api.go
platform/operations.go
shared/bravefile.go

This means that the default resources will be applied even if a Bravefile is not loaded from disk using the Load method. If the Bravefile is missing the resource limits the defaults will still be applied.

Refactor `deploy`

---

platform/operations.go

This function is currently not used, but that's probably because it doesn't behave as expected. It deletes the image alias entry leaving the untagged image behind. With this change, it now deletes the image with that name rather than the alias entry itself

Fix the DeleteImageByName function

---

platform/helpers.go
platform/host_api.go
shared/utils.go

When running `brave deploy` or `brave build` against a local image, the image fingerprint would not be returned until after the image was fully imported (we had to wait for operation to complete). As a result, interruption to build/deploy at this stage would mean cleanup code failed to work as it didn't have the image fingerprint to delete.
Instead we can get the sha256 hash from the local file on disk instead to get the image fingerprint before starting the import for local images. This allows for cleanup without race conditions.

Fix race condition in image cleanup when import local image

---

commands/commands.go
commands/info.go
platform/backend.go
platform/host.go
platform/host_api.go
platform/host_api_test.go

A host must always have a Backend due to use for resource checks so this makes sense to enforce in factory function to avoid creation of invalid BraveHosts. Conceptually this aligns with current Bravetools design - there's always a local Backend on the host used for building and deploying.
Update tests and commands to use new function. 
BraveHost.HostInfo method now returns info about the bravehost backend - its name implies and fact that it is attached to BraveHost suggests that it should only return information about current host.

Set BraveHost Backend in factory function

---

platform/backend.go
platform/multipass.go

`backend.Info` is called in the course of most bravetools commands but takes an unexpectedly long time to complete on Multipass on Windows - generally several seconds (I've seen up to 9 seconds, but more commonly 8-8.5). This makes normal usage of the tool feel slow and less snappy - for example when stopping/starting multiple units there's often a delay after each command.
This change makes the calls within multipass Info concurrent, speeding up the function by a few seconds (I've saved about 2 seconds on average, from 8.6 -> 6.4 seconds). This makes a surprisingly big difference when running many small bravetools commands sequentially.

Concurrent multipass info

---

platform/helpers.go
platform/host_api.go
platform/lxd.go
platform/operations.go

LXD server version can be retrieved using the Go client. This avoids having the odd case of multipass commands in lxd.go and helps set up for future management of remote LXD instances.

Lxd version from client

---

commands/base.go
docs/docs/bravefile.md
platform/helpers.go
platform/host_api.go
platform/operations.go
shared/utils.go

At the moment it is mandatory to specify the base image location in the bravefile. Ideally this would not be necessary - it should not matter where the image is stored. The user should simply declare which image they want and the tool should automatically retrieve it in the smartest way possible.
This PR allows bravetools to infer image location by itself if not provided. First it will check the local image store for the image, before searching the public LXD image repo. GitHub images are identified by the presence of the "github.com/" prefix, just like when using the `brave base` command.
The "location" field still exists as an optional field - when specified it takes precedence over the above image location resolution logic, so this change is backwards compatible with existing …

Resolve base image location

---

commands/init.go

Multipass VM IP address is not static by default as mentioned here https://github.com/bravetools/bravetools/issues/111. Once it changes, bravetools can no longer access the VM and cannot function.
On Windows, it's possible to use `<instance_name>.mshome.net` to reach the VM no matter what IP it has, which addresses the issue.

Win multipass dynamic ip

---

commands/commands.go
commands/init.go
platform/host.go
platform/host_api.go
platform/operations.go
platform/remotes.go
shared/constants.go

Remotes are stored in a new "remotes" folder in bravetools home dir. A remote is a human-editable json file and associates a remote with a name, address, and protocol. TLS auth for a remote is loaded if necessary.
For now, the only remote is the default bravetools local remote created during init - if all works fine then next step is to expose the ability to select and create different remotes to users.
Multiple protocols are supported for backends, allowing for use of the Unix socket when running on Linux for less overhead. This also potentially allows for storing remote "simplestreams" image stores as remotes too.

Add new remotes backend to bravetools.

---

platform/operations.go

Enforce forward slashes in path to destination within Linux container

Fix paths when copying dirs from Windows into Linux containers

---

platform/helpers.go
platform/host_api.go
platform/operations.go
shared/bravefile.go

Passing environment variables to commands in the run section of a Bravefile currently has to be done using shell commands (`sh -c 'TEST_VAR="test" ...'`). Relying on the shell is not ideal and leans into an imperative style of programming, rather than the declarative style of the rest of the Bravefile.
The LXD client provides official support for passing environment variables to `exec` commands, which works reliably and with minimal changes to the code. A small extension to the Bravefile's command to include an "env" field that exposes this would allow for an easy, declarative way to pass env variables to commands that does not involve spinning up a shell process.
Additionally, being able to avoid the `sh` command tends to make the intent of the command clearer - see the example below. …

Command env variables

---

commands/commands.go
commands/deploy.go
commands/init.go
commands/remote.go
platform/helpers.go
platform/host.go
platform/host_api.go
platform/operations.go
platform/remotes.go
shared/bravefile.go

Enables users to specify the remote to deploy to using the unit name. The first section of the unit named preceding the colon ":" will be taken as the remote name. If no remote is specified the default bravetools local remote will be used.
For example, the following Bravefile snippet will deploy a unit called "example" at the "test" remote:
```yaml:
service:
name: test:example
...
```
Also included in this is a way to specify which LXD profile to deploy the unit using, since we can no longer assume the local profile will exist on remotes. This profile can be specified in the Bravefile Service section or using a CLI flag `brave deploy --profile [name]`. If no profile is specified, the remote's default profile saved at ~/.bravetools/remotes will be used.

Remote deployment

---

platform/host.go

This pull request enables brave tools to build on remote LXD instances.
Default remote name can be specified In $HOME/.bravetools/config.yml and is used by brave tools to execute instructions on  pre-configured remotes.
name: user
trust: user
profile: user
storage:
type: zfs
name: user-20220903104341
size: 98GB
network:
bridge: 10.118.99.1
backendsettings:
type: multipass
resources:
name: user
os: bionic
cpu: "2"
ram: 4GB
hd: 100GB
ip: 192.168.64.56
status: active
remote: REMOTE_NAME 
```

add default remote name to global config

---

commands/deploy.go
commands/init.go
commands/remote.go
docs/docs/bravefile.md
platform/helpers.go
platform/host_api.go
platform/operations.go
platform/remotes.go
shared/bravefile.go

Adds ability to customize the resources an LXD container uses when deployed (Network/Storage). Primarily this allows for customizing these resources for different remote deployment targets.
Changes:
- Can specify Network/Storage/Profile to be used for deplyoment in Bravefile Service section or deploy CLI command
- Can associate a default Profile/Network/Storage with a remote, which will be used if none provided in Bravefile/CLI
- If Profile/Network/Storage still not provided, loads Host configured Profile/Network/Storage for backwards compatability
Note that selecting a disk device to launch the container with will show up when running `brave units`.
```sh
brave units
NAME            STATUS  IPV4            VOLUMES         PORTS
mongodb-amd64   Running 10.0.0.25       root:->/ …
```

Remote lxd resources

---

commands/units.go
platform/host_api.go
shared/constants.go

Addressing https://github.com/bravetools/bravetools/issues/148, this allows for listing remote units managed by bravetools.
`brave units` now lists all units across all remotes when called with no args. Each unit will be prefixed by the remote name with a colon. If a specific remote is provided, only units on that remote will be listed (with no prefix).
The remote units are identified by the profile stored with that remote to separate them from other LXD containers that bravetools does not manage. (This does mean it is preferable to assign a profile when adding a new remote).
Example:
```sh
brave units
NAME                            STATUS  IPV4            VOLUMES                         PORTS
local:mongodb-amd64             Running 10.0.0.25       root:->/ …
```

Listing remote units

---

platform/host.go
platform/lxd.go
platform/multipass.go
platform/operations.go
platform/remotes.go

This addresses the issues mentioned in https://github.com/bravetools/bravetools/issues/155.
I removed the check for devices on a unit before removing it - I think it should be fine without it.
Fix made to use network device name rather than the IP. I also updated the network bridge name selection logic to localize it to one place for clarity.

Network storage bugfix

---

platform/helpers.go
platform/host_api.go
platform/host_api_test.go
platform/operations.go

Fix postdeploy section of Bravefile when executed on remote servers and make function private.
Update tests to work.

Remote postdeploy

---

commands/start.go
commands/stop.go
platform/host_api.go
platform/host_api_test.go

This allows for management of remotely deployed units.
Remotely deployed units can now be:
- Started
- Stopped
- Deleted
In addition, the local bravetools backend VM (if on Windows/Mac) will only be started if the "local" remote is requested.
Fallback logic to filter listed units by bravetools host Profile if deploy Remote has no associated profile added.

Remote unit management

---

platform/host_api.go

When running `brave units`, only prefix remote name if it is not the local bravetools remote. If no remote is listed, the "local" remote can be assumed.
This makes output cleaner when only local units are involved. In the case of multiple remotes the units will still be grouped together by remote so there shouldn't be a loss of clarity.

Terser local unit names

---

platform/helpers.go
platform/host_api.go
platform/images.go
platform/images_test.go

Old image name schema prepended `-<version>` to the end of the image name. The new format specifies the version within the image name itself like so: `<image_name>/<version>`.
Existing Bravefiles do not work nicely with the new image name parsing - this PR adds the logic for dealing with the old image format (both Bravefiles and image files). Legacy image name parsing will be enabled when version field is passed a value in the Bravefile - suggested that new Bravefiles omit the field in favour of the new syntax.
CLI commands and Base images check both the new parsing and legacy parsing methods so existing image names can be manipulated using their names as specified in existing Bravefiles - this makes it possible to remove images by their legacy names, for example.

Backwards compatability with image fields in existing Bravefiles

---

commands/base.go
commands/build.go
commands/deploy.go
platform/helpers.go
platform/host_api.go
platform/host_api_test.go
platform/images.go
shared/bravefile.go
shared/constants.go

Addresses https://github.com/bravetools/bravetools/issues/138
This PR separates the build section of the Bravefile from the Service section. This means it's now possible to build an image from a Bravefile that doesn't have a Service section at all.
Major Changes:
- Image field added to Build section of Bravefile - structure of <image_name>[/version][/arch] just like other Image fields.
- When building image, unit name will be generated from image name (no longer requires unit Name field from Service section)
- `brave base` no longer alters the name of the image being imported. It also applies same schema as above to extract metadata (<image_name>[/version][/arch]).
Minor:
- Fixes to tests
- Passing copies of bravefile/unitParams so host_api functions can mutate them safely.
Changes were …

Brave build refactor

---

platform/helpers.go
platform/operations.go
shared/bravefile.go

Currently, if executing a command that does not exit bravetools will wait indefinitely for the completion of the command. The usual ways of running a shell command in the background don't seem to work when using bravetools. For example, using `sh -c ... &` does not detach, nor do various uses of `nohup ... &`. If the program does not provide a flag to run as a daemon process it cannot be used from bravetools without freezing the build/deploy.
Instances of programs that don't exit may include web-servers etc. that are designed to be run in the background. This means that something like starting a web-server using a post-deploy command would not work if it has no --daemon flag, like Flask.
Adding a new field to the Bravefile run command, "detach" would enable bravetools to handle such cases …

Command detach

---

platform/host_api.go
platform/operations.go
platform/resources.go
shared/utils.go

This PR makes the resource checks run by bravetools work on remote LXD instances, rather than only on the local backend.
If the remote doesn't have a specific storage device configured the early disk space check is skipped - an error will be raised when attempting to copy the image to the remote if it doesn't have sufficient space.

Remote resources

---

platform/host_api.go

Make `brave publish` work with remote units - the images will be transferred over the network and saved to local disk.

Remote `brave publish`

---

platform/backend.go
platform/host_api.go
platform/lxd.go
platform/multipass.go

Instead of erroring when local backend is not running, it is a more seamless experience if bravetools automatically starts the backend for you.
An additional benefit of this when using the multipass backend is that most bravetools commands will become far more responsive. It takes far less than a second to start the VM if it is already running, making all basic commands run quicker (previous checks took several seconds).
Since starting the VM is so quick, a progress spinner will not be displayed usually - a spinner will be shown only if the `start` command takes longer than 1 second to complete.

Ensure local Backend running

---

commands/publish.go
commands/umount.go
platform/host_api.go
platform/images.go
platform/operations.go

Publishing a unit as an image with `brave publish` now allows for naming the exported images using the new bravetools image field syntax: <image_name>[/version][/arch].
The exported image files now use the same format as bravetools image store for consistency, delimiting with underscore ("_") instead of the old legacy design that used a hypen ("-"). If no image string is provided, the default will be to export the unit as `unit_name/$timestamp` just like it is currently. This image_name/version will be preserved when the image file is imported with `brave import`.
Since the `brave publish` command can export multiple units at once, you can provide multiple image names to apply to the exported images at the CLI. This can be done either by delimiting the image names with commas or by …

Published image name

---

platform/host_api.go
platform/images.go

Small fix that avoids `failed to publish image: name and target are required` error during `brave base`

add image name to avoid error during brave base

---

platform/helpers.go
platform/host_api.go
platform/operations.go

Cleaning the paths properly avoids issues with different representations of the same path getting different hashes. Cleaning each path returns the shortest valid path, dealing with issues caused by using `..` in paths.
For example, the mount point "/root" would be hashed differently from "/root/../root" despite referring to the same directory. When unmounting, the exact same representation of the path used when originally mounting would have to be used. Cleaning the paths avoids these issues.
See [Rob Pike, "Lexical File Names in Plan 9 or Getting Dot-Dot Right"](https://9p.io/sys/doc/lexnames.html).

Clean filepaths when mounting

---

platform/host_api.go

Certain functions attempt to parse image string in modern way and fall back to legacy parsing if the image is not found.
However, this led to incorrect error reporting when the images actually did not exist and were specified in modern format - the actual error report would complain about legacy image string parsing failing.

Missing image error reporting

---

platform/helpers.go
platform/host_api.go
platform/images.go
platform/operations.go

This PR enables use of image stored in remote LXD servers in Bravefiles. These remote images can be used as "Base" images during build or as "source" images during container deployment. In addition, during the build phase it is now possible to push the resulting image into a remote LXD server.
An example Bravefile using these features:
```yaml
image: store:test-image/1.0
base:
image: store:alpine/edge
service:
name: deploy:python-api
```
**During build:**
The "store" remote provides the base image for the build phase ("alpine/edge"). The resulting image "test-image/1.0" is built and then pushed into the "store" remote server.
**During deploy:**
The "store" remote holds the source image "test-image/1.0" to be deployed as a container. If bravetools does not have a local copy of the image …

Remote image deploy

---

platform/helpers.go
platform/host_api.go
platform/images.go
platform/images_test.go
platform/operations.go

This PR changes the way bravetools stores image architectures to align with the architectures reported by the build LXD server. This  also addresses issues caused when using a remote build server that is a different architecture than the bravetools host.
Prior to this change, image architectures would be dervied from the runtime.GOARCH. For example: amd64/arm64.
After this change the LXD server reported value will be used. For example: x86_64/armv6l.
Previously bravetools used version "1.0" as a default, but this was arbitrary and could be confusing if the user actually specified 1.0 themselves. The "untagged" version makes it clearer that it is not user-provided and avoids potential conflicts.
This PR also adds image matching where partially defined images will be matched in certain …

Accurate architectures and image matching

---

platform/helpers.go
platform/host_api.go
platform/images.go

Small fixes surrounding legacy image name support.
Remove legacy parsing entirely for `brave remove -i <image_name>` CLI command due to possibility of removing the wrong image if the names/versions line up in a certain way - updating to the modern syntax should not be hard since it is a CLI command.
Return multipleImageMatches to provide reason for image match failure - this allows calling code to react based on whether image match failed due to multiple candidates or due to no candidates being found. If multiple cands, avoid attempting legacy image parsing.

Accurate architectures

---

platform/host_api.go

Check the LXD server image store rather than bravetools local imagestore when determining whether an image exists on a remote or not

Check LXD server image store for pre-existing image

---

platform/host_api.go
platform/images.go
platform/images_test.go

Legacy image filename parsing was not optional when calling `ImageFromFilename`. This could lead to problems with incorrectly parsing names with hyphens as versions. Legacy parsing should be opt in and used only in places it makes sense.
Command line commands will now default to modern image syntax. Legacy parsing reserved only for listing images in the bravetools image store.
Also included in this PR are better validation of names and improved error messaging.

Optional legacy image filename

---

platform/multipass.go

This addresses the strange decision by lxd team to change their lxd init yaml structure. Fixes #214

update preseed yaml with the latest lxd syntax

---

platform/helpers.go
platform/images.go

Using build server arch to infer required local base image architecture. Resolves issues when multiple arches exist for a given local image.
Closes https://github.com/bravetools/bravetools/issues/205

Infer local base image arch

---

shared/bravefile.go
shared/bravefile_test.go

Added check to port forwarding syntax to `service.ValidateDeploy`. Add tests ensuring this behaviour.
Closes https://github.com/bravetools/bravetools/issues/222

Early failure if incorrect port forwarding syntax 

---

shared/bravefile.go
shared/bravefile_test.go

Handle case where requested port forwarding begins with a colon - test added to cover this

Port forwarding syntax edge case

---

platform/host_api.go
platform/resources.go

Addresses https://github.com/bravetools/bravetools/issues/220
Changes:
- No longer panic when empty RAM string is provided.
- Skip network device config if no static IP requested
With this change it's possible to skip resource checks by providing an empty string "" to the values for RAM/CPU.

Resource panic

---

commands/init.go
docs/docs/cli/brave_init.md
docs/docs/init.md
docs/installation/uninstall-bravetools.md
platform/helpers.go
platform/host.go
platform/multipass.go
platform/operations.go
shared/constants.go
shared/strings.go

multipass VM will now be called "bravetools" to avoid potential collisions with existing VMs. In a multi-user scenario this bravetools VM will be shared between all users - `brave init` has been adjusted to check for existing VM.
The LXD bridge will also be shared and will be called "bravetoolsbr0".
Storage pool name is now same as LXD profile name (which is username), no longer has the timestamp. This aids discoverabiltiy in future.
Username cleaning has been removed due to strict limitations of LXD bridge names no longer being applicable.
Docs updated with latest changes.

Name multipass VM "bravetools" instead of username

---

commands/mount.go
platform/host_api.go

Addresses an bug which breaks multipass install #230 by checking if mounted volumes exist on a unit prior to deletion. Bravetools logs an error if mounted volumes are found

address #230

---

platform/helpers.go

Although username length is no longer an issue with static network bridge names, certain characters are still not permitted within names of storage pools, for instance the backslash character. Keeping the regex in place to restrict characters but remove truncation based on length.

Username cleaning

---

main.go
platform/host_api.go
shared/version.go

Pre-built binaries for bravetools did not have version info built into them and consequently the version command would return nil. For example:
```sh
Bravetools Version: <nil>
```
This was caused by dynamic lookup of a version file which does not exist alongside the binary. Instead, it's better to embed the VERSION file into the binary so it's always available for lookup.
```sh
brave version
Bravetools Version: release-2.00
```

Embed version

---

platform/multipass.go

The issue seems to be caused by commands in line 610-611 of `platform/multipass.go`
https://github.com/bravetools/bravetools/blob/8efe68e3e1dc9ee31592534686e50eef076dd924/platform/multipass.go#L610
The commands do not return complex strings that required splitting on ":" and instead seem to return the desired integer values.
The change requires testing locally of the two commands in lines 610-611 of the `platform/multipass.go` file to ensure they do not return any special characters.
Will merge when all tests confirm.

address #246

---

platform/lxd.go
platform/multipass.go

When creating a dir type storage pool it is not possible to pass a size - attempting to do so causes an error.
This is a minimal fix that only adds the size portion of the command if the storage type is not dir.
Maybe in future we could explore using the `lxc` exec for just the bare minimum server setup and then completing the rest of the setup using the Go LXD client, but that's a bigger change to make and would need some testing.

Fix dir type storage pool creation

---

commands/init.go
docs/docs/init.md
docs/installation/index.md
platform/backend.go
platform/helpers.go
platform/host.go
platform/host_api.go

Manually add a remote called "local" after `brave init --remote` with `brave remote add local ...` to setup a remote bravetools backend.

Remote bravetools backend

---

docs/docs/bravefile.md
docs/docs/build.md
platform/host_api.go
platform/operations.go
shared/bravefile.go

This implements the disk limit feature suggested here:
https://github.com/bravetools/bravetools/issues/244
By adding an additional field to the service resources you can limit the amount of disk space that a container uses.
If left blank or omitted no limit will be applied, so this is backwards compatible.
According to the [this blog](https://stgraber.org/2016/03/26/lxd-2-0-resource-control-412/) disk limits will only work when using either ZFS or BTRFS as the  storage backend. This is the default for remotes initialised by bravetools itself, but remote backends initialised separately and then added to bravetools may have different storage backends.
```
service:
name: example-service
resources:
ram: 4GB
cpu: 4
disk: 2GB
```

Limit disk

---

platform/remotes.go

Perhaps not the most elegant solution, and only tested on my Debian 12 system to build the "template" image, this PR looks at the current location of the installed lxc binary and either uses the previously hard-coded path for the "unix.socket" file or if snap is not detected uses the location that is present on my system where LXD has been installed by apt.
I will continue to test as well as work on completing the Debian packaging, but this at least unblocks my use case for now and I hope is helpful to others.

Fix non snap lxd

---

commands/compose.go

Currently bravetools has issues resolving the build remote to use during `brave compose` when bravetools was initialised with a remote backend (initialised with `brave init --remote`).
The remote to use as the build backend for compose is now configurable through the CLI, with a default remote of "local".

Remote backend compose

---

commands/init.go

Add some useful remotes during `brave init` like the LXD client. The remotes are "images" (default LXD image remote), "ubuntu" (ubuntu cloud server images), "ubuntu-minimal" (minimal cloud server images).

Pre-install remotes during brave init
